on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore
        run: dotnet restore

      - name: Update submodules # https://github.com/actions/checkout/issues/994
        run: |
          git submodule foreach 'git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*" && git fetch origin'
          git submodule sync && git submodule update --remote


      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Export
        run: |
          dotnet run paramtools \
            params convert \
            --game \
            ER \
            --input-format \
            regulation \
            --input-path \
            regulation.bin \
            --output-format \
            excel \
            --output-path \
            params.xlsx \
            --paramdex-path \
            vendor/paramdex

      - name: Upload export
        uses: actions/upload-artifact@v3
        with:
          name: params
          path: params.xlsx