on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
        
      - name: Restore
        run: dotnet restore
        
      - name: Export
        run: |
          dotnet run paramtools \
            params convert
            --game
            ER
            --input-format
            regulation
            --input-path
            regulation.bin
            --output-format
            excel
            --output-path
            params.xlsx
            --paramdex-path
            vendor/paramdex
